deploy/supervisord-ebmbot.conf, ebmbot_runner.py, environment-sample, slackbot_settings.py, tests/test_openprescribing_bot.py, tests/test_webhook_handler.py
=> Add github webhook security

deploy/fab_scripts/restart_bot.sh, fabfile.py
Ensures we pick up new configuration
=> Restart bot on deploy

bots/hal/hal.py, bots/openprescribing/openprescribing.py
...with a few other misc. fixes thrown in.
=> Send NSCO alerts from ebmbot

.travis.yml, ebmbot/webserver/__main__.py, fabfile.py, requirements.txt
This is required by our current maintenance release of pandas
=> Bump python

ebmbot/bot.py, ebmbot/dispatcher.py, ebmbot/job_configs.py, tests/job_configs.py, tests/test_dispatcher.py, tests/test_job_configs.py
=> Add report_success flag to job config

ebmbot/bot.py, tests/test_bot.py
=> Make ebmbot less sensitive to whitespace

conftest.py, ebmbot/slackbot_settings.py, tests/assertions.py, tests/test_bot.py
We don't want the default plugins to be loaded.
=> No eggplants please, we're British

ebmbot/job_configs.py
I can't see how these ever worked.
=> Fix OpenPrescribing measures commands

ebmbot/job_configs.py, workspace/team_data/generate_report.py
Adapts a script from @robinyjpark.
=> Add `team_data generate_report` command

dotenv-sample, ebmbot/dispatcher.py, ebmbot/job_configs.py, ebmbot/slack.py, tests/job_configs.py, tests/test_dispatcher.py, tests/test_job_configs.py, tests/workspace/test/jobs.py, workspace/teamdata/generate_report.py
- Update the script to generate the data team report so it can post to slack
- Adds an option to use blocks to format slack messages nicely
=> Format teamdata report for slack messages

ebmbot/job_configs.py, justfile, tests/workspace/test/test_teampipeline.py, workspace/teampipeline/generate_report.py
A first pass at a daily report for the pipeline team!
* Needs sanity checking to ensure I have the bennett bot config correct
* Do I need a different GitHub token?
Note: I'd like to check that the changes work before making a generic report that both teams can use, if possible.
=> Add pipeline team daily report

tests/workspace/test_generate_report.py, workspace/generate_report.py
This should reduce the amount of space the report takes up on screen.
=> Simplify the generated report format

tests/workspace/test_funding_report.py, workspace/funding/funding_report.py
Bugs were found in live testing
=> Fix funding report

.github/workflows/main.yml
Avoids rate limiting problems, and switches to an action that we maintain.
=> Switch to opensafely-core/setup-action for just

ebmbot/job_configs.py, ebmbot/webserver/github.py, tests/mock_web_api_server.py, tests/test_job_configs.py, tests/webserver/test_github.py
=> Configure OpenPrescribing deploy failures to go to #team-rap

docker/justfile, requirements.dev.in, requirements.dev.txt
pytest-freezegun is no longer actively maintained and has been moved into the main pytest-dev org as pytest-freezer
https://github.com/pytest-dev/pytest-freezer
=> Replace pytest-freezegun with pytest-freezer

ebmbot/bot.py
=> Respond to bennett-admin requests with suitable reaction

workspace/report/generate_report.py
- For BennettBot's daily Project Board Summary to link Alice and Tom P's tickets to their Slack profiles
=> Add Tom P and Alice's github handles

workspace/funding/funding_report.py
Reduces duplicate code by using utils functions:
- ```get_data_from_sheet``` to get the funding spreadsheet
- ```get_text_block``` to format slack text blocks
=> Refactor code for funding reports

workspace/workflows/config.py
=> Unskip airlock update-dependencies workflow

tests/workspace/test_dependabot_rota.py, tests/workspace/test_generate_report.py, tests/workspace/test_people.py, workspace/dependabot/jobs.py, workspace/report/generate_report.py, workspace/utils/people.py
Alert the person who's on the dependabot rota for this week.
=> Use slack username in dependabot reports

workspace/workflows/config.py
Notify about gh action failures for the new repo.
Repo created in https://github.com/opensafely-core/cohort-extractor/issues/1039
=> Add tpp-database-utils

tests/workspace/test_standup_rota.py, workspace/standup/jobs.py, workspace/utils/people.py
I've removed Jon from Team REX duties, since he's now moved to Team RSI and added Nishtha.
=> Add nishtha to standup rota
