bennettoxford/bennettbot

- ebmbot/job_configs.py
Small changes to match the required interface of `cohortextractor remote generate_cohort`
> Fix opensafely remote command support

- ebmbot/bot.py
- ebmbot/dispatcher.py
- tests/job_configs.py
- tests/test_bot.py
- tests/test_dispatcher.py
Special characters like `<` will break shells.
In the case of URL formatting, we remove them, but all the arguments should be escaped anyway.
> Escape job arguments for use in shells, and undo URL formatting

- ebmbot/job_configs.py
- ebmbot/webserver/__init__.py
- ebmbot/webserver/github.py
- tests/webserver/test_github.py
This adds the ability to deploy opencodelists via ebmbot.  It changes the GitHub webhook receiver to be parameterised by project.
> Add Opencodelists

- ebmbot/job_configs.py
The standard no-output-on-success behaviour is confusing in this context.
> Get import_measures command to confirm success

- requirements.in
- requirements.txt
Fixes #208 by replacing slackbot with our fork, which deals with the upcoming [changes to the slack api](https://api.slack.com/changelog/2021-10-rtm-start-to-stop)
Also upgrades other requirements.
> Replace slackbot with fork and upgrade requirements

- ebmbot/bot.py
Make sure we get all the channels for the bot to join.  Slack's docs don't say what the default limit is, but it was returning 33 results, when we have something like 87.
> Set limit to max when fetching channels

- README.md
- ebmbot/bot.py
- ebmbot/job_configs.py
- tests/test_bot.py
- Updates the README instructions for letting users dm the slack app
- Updates the main job listener to listen only for `app_mention` events, not every message
- Adds a separate listener for DMs which don't require users to @ the bot
- Adds matchers to the listener decorators to remove the need for some checks on channel type etc in the code
> Allow users to DM the bot and improve some matchers

- ebmbot/bot.py
- fabfile.py
- tests/test_bot.py
Limit the keywords for the tech-support listener to "tech-support" (with the hyphen).  It keeps the case-insensitive matching since something like "Tech-Support" is still likely to be a genuine call for tech-support help.
Also updates the matchers to ignore any messages from a bot, which means it won't repost reminders from Slackbot to e.g. check the tech-support rota
> Update tech-support matching

- requirements.dev.in
- requirements.dev.txt
We use pip-compile with `--require-hashes`, which requires all dependencies to be pinned.  One of black's dependencies isn't pinned, resulting in an error when we try to `pip install -r requirements.dev.txt` from scratch - I think this was only showing up after merging the latest PR because it was the first push to the new `main` branch
https://github.com/ebmdatalab/ebmbot/runs/8154622961?check_suite_focus=true
> Pin typing-extensions to fix error in requirements file

- ebmbot/bot.py
Reminders in slack always start with "Reminder: ", so we need to remove that text otherwise our bot will try to interpret it as a command and become confused.
Slack also likes adding in fullstops to the end of reminders, so we should remove those as well.
> Enable response to slack reminders

- ebmbot/bot.py
- requirements.prod.txt
- tests/test_bot.py
Inadvertently summoning tech support is initially hilarious but thereafter quite annoying. This PR requires that the keyword be used as a distinct word, and that it not be preceded by a slash to avoid links to our documentation triggering the keyword.
> Tighten regex for tech support keyword

- ebmbot/bot.py
- tests/test_bot.py
Reminders that @ the bot use its username as well as its ID
We need to replace this too so that bot commands in reminders will work
> Parse bot mentions in reminders correction

- .gitignore
- ebmbot/bot.py
- ebmbot/job_configs.py
- pyproject.toml
- tests/test_bot.py
- tests/test_tech_support_out_of_office.py
- workspace/techsupport/jobs.py
- workspace/test/jobs.py
Adds new jobs and commands for settings tech support out of office (on, off and status).
OOO dates are stored in the techsupport workspace as a json file.  The bot's tech support listener checks the dates, and responds with an OOO message if necessary (but still reposts to the tech support channel as normal).
Also adds the SOS reaction to acknowledge that tech-support has been summoned by the magic keyword.
Set an OOO with:
```
@bennett_bot techsupport ooo on from 2022-12-20 to 2023-01-05
```
Cancel it:
```
@bennett_bot techsupport ooo off
```
Find out the current OOO status and anything scheduled:
```
@bennett_bot techsupport ooo status
```
> Tech support out of office

- ebmbot/dispatcher.py
- tests/assertions.py
- tests/job_configs.py
- tests/test_dispatcher.py
- tests/workspace/test/jobs.py
- tests/workspace/test_generate_report.py
- workspace/generate_report.py
The data team report failed this morning (with a Slack "invalid blocks" error) because there were no tickets in one of the statuses it was trying to report on.  This fixes that bug, and also another with actually reporting the job failure to slack.
> Fix team report bug

- ebmbot/dispatcher.py
This ensures that if a failed command posts in #tech-noise, we'll notify tech support about it so someone can investigate.
> Call tech-support for failed commands

- ebmbot/dispatcher.py
- ebmbot/slack.py
- tests/mock_web_api_server.py
- tests/test_dispatcher.py
The bot doesn't register messages that it posts itself (for obvious reasons, when you think about it), so
just tagging tech-support in the message won't work. We now repost into the tech-support channel when a failed message is encountered.
> Repost messages for failed commands to tech support channel

- tests/workspace/test_generate_report.py
- workspace/generate_report.py
We'd made too many assumptions about the ordering of result from GH's API.
No new tests sinc existing code is untested.
> Fix data team report

- DEPLOY.md
- ebmbot/settings.py
- workspace/techsupport/jobs.py
This makes a more general use writeable dir setting, for any jobs that need to write files. Currently, in addition to fabric jobs, we have the tech support ooo job that writes the OOO status to a file.
> Add a WRITEABLE_DIR setting for jobs that need to write files

- ebmbot/bot.py
- ebmbot/slack.py
- tests/conftest.py
- tests/test_bot.py
- tests/test_dispatcher.py
On Friday Rich tried to run an op command, but nothing happened
https://bennettoxford.slack.com/archives/CGF9TKZLG/p1704475634495869
`@BennettBot status` suggested that [this request](https://bennettoxford.slack.com/archives/CGF9TKZLG/p1704192282113689) to run a measures preview from 2nd Jan was still running, so the new request was just scheduled. Something apparently happened that meant the job didn't report that it either failed or succeeded, but I can't see far enough back in the old logs to see if anything was logged. In any case, the "running" job blocked any attempts to retry it, so this PR adds a command to remove a job by id in case this happens again.
Although I can't see if it was the case for the 2nd Jan job, there was an instance of an uncaught error from slack 
``` …
```
> Catch slack errors and add a command to remove jobs

- Procfile
- docker/docker-compose.yaml
- ebmbot/webserver/__main__.py
- gunicorn/conf.py
- pyproject.toml
The webserver in BennettBot is a Flask app; as per flask [docs](https://flask.palletsprojects.com/en/3.0.x/tutorial/deploy/#run-with-a-production-server) using app.run is intended for development only. As we've now moved to the new dokku app, update to run with gunicorn as well.
> Run webserver with gunicorn

- ebmbot/dispatcher.py
- ebmbot/job_configs.py
- tests/test_dispatcher.py
- tests/test_errorlogs.py
- workspace/errorlogs/show.sh
When a bot command fails, it returns a message that says where the logs can be found, but it's quite tedious to ssh to dokku3 in order to check what went wrong. This adds two new commands `errorlog head /path/to/log/dir` and `errorlog tail /path/to/log/dir` that let us check the error logs from slack.
It's slightly more complicated than just a `head`/`tail` on the log file, because we need the bot to read from the log folder in its mounted storage volume rather than the location in the host filesystem.
> Add commands to show head/tail of error log files for failed bot commands

- DEPLOY.md
- Procfile
This wasn't needed with fabric3, but now we've replaced it with fab-classic (and paramiko with paramiko-ng), the ssh key in the mounted ebmbot user's home directory wasn't being recognised and it hung asking for a password. It needs to be explicitly added with ssh-add. I'm not sure the Procfile is the place I really want to do it, but it's the only way I found that worked. The "release" command is run before containers are deployed, and a post-deploy command in app.json also doesn't run in the containers afaict.
(I did also try explicitly telling fabric which key file to use with the `-i` option, to no avail.
> Add the docker user's ssh key with ssh-add

- ebmbot/dispatcher.py
- ebmbot/job_configs.py
- workspace/errorlogs/show.sh
In my local testing at least, printing larger log files just split the content over multiple slack messages, rather than causing an error.
It's less pretty than tail/head, because we can't wrap it all in code blocks, but it does seem to be fine to show the entire error log content.
> Add an option to show whole error log

- ebmbot/bot.py
- ebmbot/job_configs.py
- ebmbot/slack.py
- tests/job_configs.py
- tests/test_bot.py
- tests/test_job_configs.py
Some extra user help that came out of my show-and-tell:
- add a description to each category of available slack commands to display in the main `@BennettBot help`
- Label namespaces "categories" in the help message (Fixes #34)
- Post helpful error messages back to slack if an unexpected error is caught by the error handler
> More useful help and error messages

- ebmbot/bot.py
- ebmbot/scheduler.py
- tests/assertions.py
- tests/test_bot.py
- tests/test_scheduler.py
If a user asks BennettBot to do something, and a job of the same type is already running, the job is scheduled to start once the running job completes.  A job might actually be running, but on occasion a job errors in an unexpected way, so the database isn't updated to fail or complete the job, and the new job will never start (until the old one is manually removed).  This just adds some feedback for the user if their job is being queued.
Fixes #398
> Notify users if a job is already running

- ebmbot/bot.py
- ebmbot/connection.py
- ebmbot/dispatcher.py
- ebmbot/scheduler.py
- tests/test_dispatcher.py
Users can have DMs with BennettBot, but they can't call tech-support from DMs, because no-one else will be able to access the message. If a user tries to run a job from a DM with BennettBot, and it fails, it should also not repost to tech-support when it reports the failed job.
> Don't repost to tech-support from DMs

- README.md
- ebmbot/bot.py
- ebmbot/job_configs.py
- tests/job_configs.py
- tests/mock_web_api_server.py
- tests/test_bot.py
- tests/test_job_configs.py
Add minimal restrictions that can be applied to categories of jobs, to restrict the entire category to internal users.
For every slack message event sent, the slack API includes a user id, which we can look up to get the value of `is_restricted`, which is True if the user is a guest (i.e. external) user.
I've updated the job config to restrict the jobs that I think we care about - op, fdaaa, funding and techsupport (techsupport for the out of office on/off commands, not the rota).  For the others, I don't _think_ we're concerned about external users seeing the project boards, logs, or outputchecking rota.
> Option to restrict jobs to internal users only

- ebmbot/bot.py
- tests/test_bot.py
Second attempt at this with better testing :)
Editing a message to include the tech-support keyword should SOS it and repost it to the tech-support channel. If it was already SOS'd (because the edit is to something other than the keyword), the attempt to react again will fail and be caught by the error handler - which is fine and what we want.
Note that we have to use `@app.event` in order to filter to message subtypes, and not `@app.message`; this also means that we have to include the tech-support keyword regex matcher in the event matchers ourselves (`@app.message` takes a regex and does the matching for us).  This is what went wrong before!
> Respond to edited tech support messages

- ebmbot/bot.py
If a user has been removed, they are still returned in the users list, but the "is_restricted" field isn't present
> Fix bug in get_users_info for old users

- DEPLOY.md
- README.md
- ebmbot/job_configs.py
- ebmbot/slack.py
- tests/conftest.py
- tests/job_configs.py
- tests/test_dispatcher.py
- tests/workspace/test/jobs.py
- workspace/showlogs/show.sh
Addresses the second part of #432 
Slack can handle messages of up to 40K characters, but it will split content across messages, with a maximum of 4000 characters in each message. This breaks our nice code formatting for the showlogs commands.
We could split the message, wrap each chunk in triple backticks and post each message separately - this works, but it's not guaranteed to split the message in sensible places, and breaking across messages isn't great.  If the message is > 4000 characters, we now upload it as a file snippet instead.  Currently this is only done by default for jobs with `code` format specified, so very long plain text messages will still go across multiple messages - but we don't have any of those atm anyway, and there is now a new option to specify `file` as the …
> Improve output for showlogs commands

- ebmbot/dispatcher.py
This means responses to commands will get posted as replies rather than as new messages in the channel. The job entry already stored the thread_ts, it just wasn't being passed into the slack notification.
Fixes #432 (along with #436)
> Pass thread_ts to successful job notification

- ebmbot/bot.py
Use thread_ts from the original message instead of ts when scheduling jobs. thread_ts may not be present when a command is called directly (not from a thread), which is fine, because the response will be posted into the channel as a new message, which is what we want. It will now only be posted as a reply if it was called from within a thread.
> Pass thread_ts instead of ts to scheduled jobs

- ebmbot/job_configs.py
- tests/test_dependabot_rota.py
- tests/workspace/dependabot-rota.csv
- workspace/dependabot/jobs.py
This will remind us when to check Dependabot PRs based on a rota in a Google Sheet.
> Dependabot rota report for Team REX

- ebmbot/job_configs.py
Something about the way fabric/ebmbot work means that stderr gets reported to Slack, interspersed with stdout. This flag disables the stderr logging to stop the command creating a lot of noise in a Slack.
If there's a simple way to get it just report stdout that would also solve the problem, but I couldn't immediately see one.
See also:
* https://github.com/ebmdatalab/openprescribing/pull/4772
> Add `--quiet` flag to NCSO alerts command

- .pre-commit-config.yaml
- tests/test_techsupport_rota.py
- workspace/techsupport/jobs.py
These are changes made in response to #552 (plus changing the precommit config to use python 3.12 instead of 3.8)
- BennettBot now shows the Tech Support rota for the current week and next week regardless of whether it is a Monday. 
- `test_rota_report_on_monday` and `test_rota_report_on_tuesday` are both kept even though now the behaviour does not vary between Monday and Tuesday, as a good-to-have
- As noted in the Issue, dates are now added to the reports
- For convenience, BennettBot now also provides a link to the rota spreadsheet 
- Precommit config yaml now uses Python 3.12 instead of 3.8 to be consistent with the rest of the repo
> Add dates to tech support rota reports and modified to show any day of week

- tests/test_dependabot_rota.py
- tests/test_outputchecking_rota.py
- tests/test_techsupport_rota.py
- workspace/dependabot/jobs.py
- workspace/outputchecking/jobs.py
- workspace/techsupport/jobs.py
Continues from PR 562. Fixes #552 .
- Date format changed to %d %b for readability
- Outputchecking and dependabot rota now show dates and link to google spreadsheet, consistent with techsupport rota
- Dependabot rota now shows both this and next week purely to be consistent with the other rotas
- Duplicate code is present in all the jobs.py files in the three workspaces. This is deliberate as the duplicate code can be removed easily when addressing #553 .
> Make outputchecking/dependabot rotas callable any day of the week

- .gitignore
- DEVELOPERS.md
- dotenv-sample
- ebmbot/job_configs.py
- scripts/local-setup.sh
- Set local WRITEABLE_DIR to a different location to workspace/
- Add docker environment variables to dotenv-sample and docs, to specify paths that need to be different when running in docker rather than locally
- Add a test job for testing fetching remote files and using them to run jobs (because we can't run fabric jobs locally, and those are the only ones that do this)
> More local setup improvements

- README.md
- ebmbot/dispatcher.py
- tests/test_dependabot_rota.py
- tests/test_outputchecking_rota.py
- tests/test_techsupport_rota.py
- workspace/dependabot/jobs.py
- workspace/outputchecking/jobs.py
- workspace/techsupport/jobs.py
- workspace/utils/blocks.py
- workspace/utils/rota.py
- workspace/utils/spreadsheets.py
Fixes #553.
- Currently BennettBot handles 3 different rotas which results 3 files in 3 different namespaces containing duplicate code
- To remove duplicate code, create ```utils``` modules called ```rota``` and ```spreadsheet``` to hold the common code
- Create the ```RotaReporter``` base class and inherited classes for each rota
- In order for the utils module to be detected, the PYTHONPATH set for the dispatcher had to be changed to be the root of the application. ```README.md``` is updated accordingly
> Share code between different rota reporting functions

- ebmbot/dispatcher.py
search.messages is tier 2 rate limited in slack, which allows around 20 calls per min. Our 2 calls per loop every 5 seconds was - just - exceeding this, so increasing it to run every 10 seconds should hopefully be safe.
> Increase the delay for the MessageChecker loop

- ebmbot/slack.py
- tests/test_utils.py
- workspace/funding/funding_report.py
- workspace/report/generate_report.py
- workspace/utils/blocks.py
- workspace/utils/rota.py
- A job can encounter no errors in its bash command execution but fail to post its results to Slack. This is a rare scenario but it can happen e.g. due to incorrect block formatting.
- Currently for such jobs the way to check the error is to go into the dispatcher logs
- Adding functionality for BennettBot to directly post the error into the chat
- In the process, utils functions for block formatting were created, which resulted in some refactoring done for other bits of code in the repo.
> Have Slack send an error message if a message failed to post

- ebmbot/dispatcher.py
- tests/test_dispatcher.py
Not sure how this got in - probably a VSCode autocomplete that somehow went unnoticed. Have also added the missing test assertions that would have caught it.
> Fix typo in MessageChecker

- ebmbot/bot.py
- ebmbot/dispatcher.py
- ebmbot/slack.py
- ebmbot/webserver/github.py
- tests/test_bot.py
- tests/test_dispatcher.py
- tests/test_notify_slack.py
- tests/webserver/test_github.py
Fixes #6 
Depends on #576 
Notify in slack when a PR is merged and deploys are suppressed. This currently only applies (I think) to OpenPrescribing, which uses the webserver as a callback when PRs are merged to main. BennettBot will schedule a deploy job, however if there is already a deploy suppression in place, it looks like nothing has happened. (You could call @BennettBot status to see that the job is scheduled and the suppression is active, but that's not obvious).
Now we post a message (in the job's default channel, which is usually #tech-noise for these sorts of things) to notify the user.
Also adds confirmation messages for scheduling and cancelling suppressions, as those both respond with :crossed_fingers: as with other jobs, but don't give any other indication that they've …
> Notify users about suppressions (when scheduled, cancelled, or affecting deploy on PR merge)

- ebmbot/job_configs.py
- workspace/workflows/jobs.py
I left a TODO comment thinking that I can share some code between `workflows/jobs.py` and `report/generate_report.py`, but the differences between what's being done is actually larger than I thought, so I'm getting rid of the comment. 
Also tiny improvement to the help message so that `org` doesn't look like a command.
> Remove #TODO and minor change in help message

- bennettbot/job_configs.py
- tests/workspace/test_workflows.py
- workspace/workflows/jobs.py
- We want to create an automated slack reminder to show the emoji dashboard for repo workflows.
- It is better for that reminder to show all three organisations (opensafely, opensafely-core, ebmdatalab) in one dashboard instead of having to create three separate dashboards
- Added a "show all" command that shows the status of all repos listed in `config.py`
> Create "show all" command

- bennettbot/bot.py
- tests/test_bot.py
Fixes #35.
- The colon in HH:MM is now optional.
- The error Slack message now says "Wrong time format - `[start_at]` and `[end_at]` must be HH:MM with `[start_at]` > `[end_at]`" so that it's clearer to the user what went wrong.
- Technically the "must" in the above sentence is now a lie, but there is probably no harm since the above wording is clearer than saying something like "HH:MM or HHMM".
> Making the colon optional for HH:MM in _get_datetime regex

- bennettbot/bot.py
- tests/test_bot.py
Fixes #58.
- Slack would often automatically identify URLs in commands to Bennett Bot and would format them as link text ( `<www.foo.com|www.foo.com>`)
- Alter the existing `_remove_url_formatting` function to correctly strip the link text when parsing the command and only pass the URL on.
> Strip link text when passing urls to Bennett Bot

- tests/workspace/test_workflows.py
- workspace/workflows/config.py
- workspace/workflows/jobs.py
Fixes #586 .
- There is a dictionary of workflows that do not run on the main branch in `config.py` called `SKIPPED_WORKFLOWS_ON_MAIN`. This has now been updated with brief comments are now added to show what each ignored workflow is.
- There is one workflow marked with #TODO following [this conversation on Slack](https://bennettoxford.slack.com/archives/C069YDR4NCA/p1727345417986209)
- Workflows that are not in `SKIPPED_WORKFLOWS_ON_MAIN` but are still missing now show up as ghost emojis. Previously these were printed to `stderr` as a warning. The current approach is better as it prompts the reader to review why the workflow was not found to be run on main. If there is a legitimate reason behind, the workflow ID can be added to `SKIPPED_WORKFLOWS_ON_MAIN`.
- As part of this PR, the …
> Update list of skipped workflows and show missing workflows as ghost emojis

- bennettbot/dispatcher.py
- bennettbot/logger.py
- tests/test_dispatcher.py
The standard bot matcher already does this, but the message checker was reposting messages that include tech-support only within a URL.
Also updates the logging config to log INFO and above in production. The constant debug log messages were making it hard to check logs to find out what it was and wasn't responding to.
> Ignore tech-support keywords that only appear in a URL

- .github/dependabot.yml
Due to a bug in httpretty v1.1.0, we need to keep it pinned. Stop dependabot trying to upgrade it.
See https://github.com/gabrielfalcao/HTTPretty/issues/425
> Don't allow dependabot to upgrade httpretty

- .gitignore
- bennettbot/settings.py
- tests/workspace/test_workflows.py
- workspace/workflows/jobs.py
Fixes #597.
- Cache workflow run conclusions in a JSON file (git-ignored), and only retrieve workflow runs from GitHub that have occurred since the last cache.
- This reduces the number of workflow run results being requested from GitHub and reduces the time taken for the job. (More written in the issue).
- The is a timer function taken from time-workflows that was added, used to measure the speed of various parts of the code, then removed. I have not erased it from the commit history as it is likely that I, a junior dev, might want to use it again and would like to find it from the commit log.
> Cache workflow run conclusions 

- bennettbot/dispatcher.py
- tests/test_dispatcher.py
It seems like slack's search sometimes takes a while to pick up certain messages.
E.g. [this message](https://bennettoxford.slack.com/archives/C31D62X5X/p1727814632973539) from Rich didn't get SOS'd when he posted it. When I tried searching slack (in the UI, not with the API) a few minutes after the message was posted, it wasn't returning it in the search results when I searched using the BennettBot message checker query. It only came up if I also explicitly put `from:@<rich>` into the query.
However, this morning the search UI (and the API) are returning that message. So, I think some messages slip through the cracks somehow, don't get sent to our slack bolt app, and also don't get returned in search results. But they do get picked up some time later. Rich's message was sent at 9:30pm, …
> More updates to the message checker

- bennettbot/job_configs.py
- tests/workspace/test_workflows.py
- workspace/workflows/jobs.py
- The emoji key for the workflows dashboard takes up space and probably does not need to be shown daily. Hide it from the daily report and define a separate job to show the key.
- Users can now click the repo name to jump to the GitHub actions page in the browser instead of the "(link)" text after the emojis. This makes the report look less cluttered.
> Readability improvements for workflows dashboard

- bennettbot/bot.py
- tests/test_bot.py
Fixes #583 
Allows us to match commands that follow an @BennettBot mention, even if they are preceded by other text. It's quite common to copy/paste a previous bot command, and accidentally paste a bit of preceding text. We'll now ignore anything that preceded the @BennettBot mention.
We already handled extra whitespace and a following ".". I haven't attempted to handle additional text that follows a command, because a) it's probably not encountered that often and
b) it would be complicated to try and match any job command regex when we don't have a definite fixed list (we sort of do at any one time, but it can be added to, and we don't test all combination), and a number of job commands are subsets of others (e.g. `test hello` and `test hello [name]`) and so would be dependent on being …
> Extend the text matcher for bot commands

- bennettbot/job_configs.py
- tests/workspace/test_workflows.py
- workspace/workflows/jobs.py
Mainly fixes #603 but there are additional changes.
- Added a `show-failed` job that gives a dashboard where the repos with all-green status are not shown. This is expected to be the main dashboard shown daily in the tech channel. (see comment in #603)
- Repos in the summary dashboard generated by `show all` are presented in ascending order of their success rate. Essentially this puts the repos with unsuccessful workflow runs at the top of the dashboard and prevents them from being truncated in the Slack message.
- After discussion with @rebkwok, there is little need to report workflow run statuses for any branch other than `main`, so the functionality to retrieve/cache other branches is removed. This simplifies the code and the tests.
- Additional structural changes to the code accompany …
> Only show repos that have unsuccessful workflow runs in daily dashboards

- bennettbot/job_configs.py
- tests/workspace/test_workflows.py
- workspace/workflows/config.py
- workspace/workflows/jobs.py
- The team associated for each repo is now hard-coded in the config
- The "show all" and "show-failed" jobs present the repos in sections for each team
- Following [this comment](https://github.com/ebmdatalab/bennettbot/pull/602#discussion_r1784331892), use subparsers for the command line arguments
- For reports on single repos, one can now type just the repo name instead of `org/repo` (e.g. `workflows show airlock` instead of `workflows show osc/airlock`). The `--help` message was not changed to avoid unnecessary confusion (as it is already very long). It might be a good idea to later define a `workflows targets` job that just prints guidance on valid values for `[target]` instead.
> Section the "show all"/"show-failed" reports by team

- tests/workspace/test_workflows.py
- workspace/workflows/config.py
- workspace/workflows/jobs.py
- There are a couple of known failures (check links, dependabot updates) that are appearing daily and creating clutter
- Register these known failures in the `config.py` and hide them when creating summaries
- From the [Slack convo](https://bennettoxford.slack.com/archives/C01SE1WB6AW/p1728997930694689?thread_ts=1728994626.948159&cid=C01SE1WB6AW), still show them when the `target` is a specific repo, not a summary
It would be better to make this an optional configuration - explore in https://github.com/ebmdatalab/bennettbot/issues/618
Previous iteration of this PR: https://github.com/ebmdatalab/bennettbot/pull/617
> Hide currently known failures from the summary dashboards

- bennettbot/bot.py
- bennettbot/config.py
- bennettbot/dispatcher.py
- tests/test_bot.py
- tests/test_dispatcher.py
The bennett admins channel name was recently changed, which required a change to the production environment variable, because our settings used channel names and not channel ids. There are benefits to being able to use both. 
Most slack functions will accept either a channel name or a channel ID. We always use a channel ID for support channels for the few functions that require it. For readability, our settings have used channel names, but the disadvantage is that if a channel name changes, bennettbot will no longer be able to post to it.
This allows settings to be either channel name or channel ID. If we decide to change them to channel IDs in prod, this means channel names can be changed with no interruption to how the support keywords work. 
Most of the changes in this PR are actually …
> Allow support channel settings to be either channel name OR channel ID

- bennettbot/dispatcher.py
- docker/entrypoints/prod.sh
- justfile
- tests/job_configs.py
- tests/test_dispatcher.py
In local dev environments, we run with `just`, which explicitly
uses the virtual env bin to run all commands, without the
user needing to manually activate it. However, dispatcher jobs are
run in a subprocess and just run with `python ...` and so don't
automatically use the virtualenv python.
In the Dockerfile (i.e. for production), we prepend the virtualenv
bin path to the PATH environment variable, which ensures that the
virtualenv python will be the first python encountered and used.
We now check for an ABSOLUTE_BIN env variable (set in the justfile, so this
will only apply for local envs, not prod) and ensure that it is first
in the PATH when running a job.
Note that we could set PATH itself in the justfile so that it is passed
through in os.environ to the job subprocess, but if we …
> Use the correct python version when running jobs 

- bennettbot/job_configs.py
- tests/workspace/test_workflows.py
- workspace/workflows/config.py
- workspace/workflows/jobs.py
- Bug 1: An empty message is sent to Slack when `show-failed` has no failing repos to report. Now a custom message is sent.
- Bug 2: `show-all` falls over when all the workflows in a repo are skipped due to being known failures. Now the repo is skipped.
- Added a custom `workflows check-links` job to report only the workflows for link-checking on Bennett websites - see [Slack conversation](https://bennettoxford.slack.com/archives/C01SE1WB6AW/p1729095341110609)
- The tests that call `main` have been refactored to use the new `use_mock_results` decorator instead.
> Fix bugs and add custom `check-links` job

- workspace/report/generate_report.py
Add new Team REX member GitHub usernames so they can be tagged in daily project boards. Added Katie, Mary, Mike.
Sort dictionary literal by GitHub username key as slightly easier to navigate and this was the intent prior to recent additions.
Add function docstring.
> Add new #team-rex member GitHub usernames

- workspace/workflows/config.py
It now runs only for GithubActions, and is no longer an expected fail.
> Unskip dependabot workflow for repo-template

- tests/workspace/test_workflows.py
- workspace/workflows/jobs.py
Fixes #628.
Workflow statuses get updated since creation, and we want to show the most recent status. 
We dealt with changes from pending to completed statuses before but that method is insufficient to deal with manual reruns of workflows, which can lead to changes from one completed status to another (e.g. "failure" to "success").
If a workflow run has not succeeded at its time of creation, we consider there to be a possibility for a status update to have occurred since the last retrieval. In such cases, fetch the results without the `created` query parameter to make sure we are getting the latest statuses.
> Call the API without creation timestamp filter if there are potential status updates

- tests/workspace/test_workflows.py
- workspace/workflows/jobs.py
Fixes #633.
In the following scenarios, return a Slack message instead of falling over and notifying tech support
- Invalid input: Slack message about input format and valid organisations (`report_invalid_org` is now `report_invalid_target`)
- Unexpected error calling `workflows show` or `workflows show-failed`: Slack message containing the error and the `target` variable
- Unexpected error calling other `workflows` jobs: Slack message containing the error
Also fixes the problem that actually prompted the multiple failures this morning, which is the website repo names being prepended by "http://" by Slack
> Do not notify tech support if a workflows reporting job fails

- workspace/workflows/config.py
The "Update python dependencies" workflow is currently broken and is in the process of being fixed (see [ticket](https://github.com/ebmdatalab/metrics/issues/250)), so we don't want to alert on it right now.
> Skip some Metrics repo PRs

- docker/dependencies.txt
distutils has been deprecated for some time, and was removed from 3.12's standard library ([PEP 632][]). Recently, python3.12-distutils was also removed from deadsnakes. Including it in docker/dependencies.txt breaks the build; removing it from this file seems to be harmless, probably because tools that depend upon it have already migrated to setuptools.
[PEP 632]: https://peps.python.org/pep-0632/
> Remove distutils

- workspace/codespaces/codespaces.py
JSON represents boolean values as `"true"` and `"false"`. `requests` deserializes these correctly as `True` and `False`, meaning there's no need for the equality tests.
> Fix `get_codespace`

- bennettbot/job_configs.py
I tested this in Slack and while the weekly report works fine, the daily one isn't being passed the day_of_week argument. This PR should fix that.
> Pass in day_of_week argument

- tests/workspace/test_dependabot_rota.py
- tests/workspace/test_people.py
- workspace/dependabot/jobs.py
- workspace/outputchecking/jobs.py
- workspace/report/generate_report.py
- workspace/techsupport/jobs.py
- workspace/utils/people.py
- workspace/utils/rota.py
> Remove Team REX dependabot rota spreadsheet

- workspace/codespaces/codespaces.py
Revert to using `print` in output and no `json.loads`. 
Since https://github.com/ebmdatalab/bennettbot/commit/c086fa0d12aa3c879b9493768c8d4b659ee944ed was pushed, the bot has stopped printing output when the command is run. From looking at the logged output, I think this is the culprit: it can't interpret the prettified text as it expects for display in Slack.
> Codespaces report: hotfix for output

- workspace/workflows/jobs.py
[Slack thread](https://bennettoxford.slack.com/archives/C63UXGB8E/p1736229649367949)
Skip reporting workflows being missing in summary reports. The behaviour for repo reports remains unchanged for now.
> Skip reporting missing workflows in summaries

- .github/workflows/main.yml
- DEPLOY.md
- bennettbot/job_configs.py
- docker/Dockerfile
- docker/docker-compose.yaml
- workspace/workflows/config.py
* some of these things will auto-redirect from the old name, although not ghrc.io
> Move bennettbot to bennettoxford Github org

- requirements.dev.in
- requirements.dev.txt
- tests/mock_http_request.py
- tests/test_bot.py
- tests/test_dispatcher.py
- tests/test_notify_slack.py
- tests/webserver/test_github.py
- tests/workspace/test_workflows.py
httpretty has not been actively maintained for a while (there are a lot of outstanding PRs and issues, and the last commit on main was 3 years ago). We were already pinning it because of one [bug](https://github.com/gabrielfalcao/HTTPretty/issues/425), and it's now also [incompatible with the latest version of urllib3](https://github.com/gabrielfalcao/HTTPretty/issues/484), which is why the latest update-dependencies PR is failing.
[mocket](https://github.com/mindflayer/python-mocket/) does all the same things as httpretty and more (it does have a plugin that aims to be a dropin replacement for httpretty, but it doesn't cover all the ways that we use it). In any case, replacing our use of httpretty with mocket is quite straightforward.
> Replace httpretty with mocket

- .github/workflows/update_dependencies.yml
* it doesn't need to be a secret, only the key does
* the var has already been set
> Retrieve the app id from vars rather than secrets

- bennettbot/job_configs.py
- workspace/codespaces/codespaces.py
Allow the Slack request to specify the threshold rather than hard-coding it. We
may fine-tune this depending on how much output we get and what proves most
useful to users. This makes it easier to do that experimentation, change Slack
reminders etc.
I'll update the playbook with the current threshold and rationale. That'll be a
separate PR as it's a separate repo (team-manual).
As discussed in Slack:
https://bennettoxford.slack.com/archives/C069SADHP1Q/p1736434022622129?thread_ts=1736427127.238419&cid=C069SADHP1Q
> Parametrize threshold

- DEPLOY.md
- bennettbot/job_configs.py
- bennettbot/settings.py
- bennettbot/webserver/github.py
- workspace/workflows/config.py
* the redirect means this will work using either org name, but we should amend
> OpenPrescribing has moved to the new GH org

- bennettbot/job_configs.py
- tests/workspace/test_workflows.py
- workspace/workflows/config.py
- workspace/workflows/jobs.py
Addresses #610, albeit not in the exact way described in the ticket, and brings additional changes. 
#610 wanted to add a `show-multiple` job: This is not done, instead the `show` command is now able to take a comma-separated list.
#610 also wanted to incorporate `check-links` into `show`: This has been done, but maybe slightly differently from what the ticket implied:
- While `show documentation,bennett.ox.ac.uk,opensafely.org,team-manual` is now a valid command, it will show all workflow statuses for all those repos. This results in more clutter than the current approach, so ...
- `show check-links` exactly replaces the existing `check-links` command, where only the specified workflow IDs (for link checking) are shown. I believe this is more suited to the use case and should be kept. …
> Tidy up workflows commands

- bennettbot/job_configs.py
- tests/workspace/test_workflows.py
- workspace/workflows/jobs.py
The bot is always going to run `python jobs.py show --target target` with `target` as a single string in quotes.
i.e. it will always be running `python jobs.py show --target 'os osc'` and never `python jobs.py show --target os osc`.
Given that it is unlikely for anyone other than the bot to be running the command, there is not really any need to support the latter scenario, so the code can be simplified.
> Simplify the  `show --target` parser argument

- tests/workspace/test_people.py
- tests/workspace/test_standup_rota.py
- workspace/dependabot/jobs.py
- workspace/report/generate_report.py
- workspace/standup/jobs.py
- workspace/utils/people.py
Fixes #695.
This uses the new people-related data structures and allows users to be named by Slack username in the `standup daily monday` repo, @-ing them in Slack. I tested this in the test Slack workspace (temporarily changing my own slack username locally as the username string is different per workspace apparently).
I don't think the `DependabotRotaReporter` class is suitable for this report as that cycles through a list of candidates and reports one of them each week, whereas the standup rota reports 6 people in a certain order each week, with the ordering alternating between "even" and "odd" weeks.
Also some changes to the class and test design that are hopefully beneficial, see individual commit messages.
> Standup rota: Use people-related classes and notify them in Slack

- bennettbot/job_configs.py
- tests/job_configs.py
- tests/test_bot.py
- tests/test_dispatcher.py
- tests/test_job_configs.py
Fixes #704 .
- Add a validation in `build_config` that checks that a given parameterised Slack command has parameters that matches the `run_args_template` for the corresponding job
- Since `build_config` is run on all our jobs whenever a unit test file imports `job_configs`, a run of all tests (locally or in CI) will trigger the validation and catch any errors in the `raw_config`
> Validate that a parameterised Slack command matches the corresponding `run_args_template`

- tests/workspace/test_dependabot_rota.py
- workspace/dependabot/jobs.py
A link to a [combined view on all our repos](https://github.com/pulls?q=is%3Apr+is%3Aopen+repo%3Aopensafely-core%2Fjob-server+repo%3Aopensafely-core%2Fopencodelists+repo%3Aebmdatalab%2Fmetrics+repo%3Aopensafely-core%2Freports+repo%3Aopensafely-core%2Factions-registry+repo%3Aopensafely-core%2Fresearch-template-docker) may be a useful way to identify PRs for review. This is in the Slack report workflow that we get each Monday telling us who's turn it is and what to do.
> Dependabot Slack repo: add combined link

- workspace/workflows/config.py
- workspace/workflows/jobs.py
[Slack conversation](https://bennettoxford.slack.com/archives/C63UXGB8E/p1739781342162469?thread_ts=1739273253.689819&cid=C63UXGB8E)
- The `SKIPPED_WORKFLOWS_ON_MAIN` dictionary can be used more generally to contain any workflows we would like to ignore (e.g. a disabled workflow). Rename it to better reflect its more broad purpose
- Ignore the disabled CodeQL workflow in backend-server (ID retrieved from https://api.github.com/repos/opensafely-core/backend-server/actions/workflows)
> Rename SKIPPED_WORKFLOWS_ON_MAIN and ignore CodeQL in backend-server

- tests/test_job_configs.py
- tests/workspace/test_workflows.py
- workspace/workflows/jobs.py
After #710, we now have a general ignore list of workflow ids. 
- Add an `if` statement to handle the case where runs for an ignored workflow is found - "handle" here of course means "dropping it".
- Add a corresponding unit test
> Ignore runs if not in self.workflow_ids and add corresponding test

- bennettbot/job_configs.py
- tests/workspace/inbox-rota.csv
- tests/workspace/test_inbox_rota.py
- workspace/inbox/jobs.py
Add a workspace to report the team inbox rota.
At the moment there is only one email address (team@opensafely.org) that has such a rota, so there is only one job (report_rota). If there are more inbox rotas in the future, some renaming/refactoring will be needed.
> Add inbox rota report

- bennettbot/job_configs.py
- tests/test_utils.py
- workspace/report/generate_report.py
- workspace/utils/argparse.py
- workspace/workflows/jobs.py
The `report board` command asks to pass multiple statuses as a comma separated string in the Slack message.
It appears that there is no code to parse and split the comma separated string, maybe it has been lost in previous changes.
(Re-)implement this using an `argparse.Action`.
Testing:
The `report teamrex` and `report teamrap` commands have also been tested.
> Parse Github project board statuses as a comma separated string

- bennettbot/job_configs.py
- workspace/report/generate_report.py
- workspace/utils/shorthands.py
- workspace/workflows/config.py
- workspace/workflows/jobs.py
- This will allow the user to get boards outside of the opensafely-core
org on Slack.
- Since the boards fetched by Bennett Bot might be internal or private,
restrict all the report commands to internal users only.
The second and third commits comprise a quality of life change to avoid the user having to type the full organisation name to call the command.
> Require `org` parameter in `report board` command

- workspace/workflows/config.py
We're not updating dependencies in cohort-extractor and dependabot workflows is now failing because it doesn't support python 3.8. It's currently in the process of being fully deprecated, so we can stop checking it here.
> Remove cohort-extractor from workflow reports

- bennettbot/dispatcher.py
- bennettbot/job_configs.py
- tests/job_configs.py
- tests/test_dispatcher.py
- tests/test_job_configs.py
Some jobs alert tech support on failure, but there is nothing much that tech support can do. We can add a key to the job config dict called `"call_tech_support_on_error"`.
If this is explicitly set to `False`, then Bennett Bot won't repost the failure message to the tech support channel. 
Closes #635 
(Not adding a command but adding a config)
> Allow configuration for whether a job calls tech support upon failure

- bennettbot/job_configs.py
Blocked - needs to be merged after #763 
The default channel for OpenPrescribing jobs should now be `#openprescribing`, not `#team-rap`.
Also do not call tech support for the failure of any OpenPrescribing jobs, as the tech support person would just be reposting the errors to the `#openprescribing` channel.
> Update OpenPrescribing job configs
